#ifndef APP_CONST_IEC104_H
#define APP_CONST_IEC104_H

#include "app_const.h"

//
#define APP_CONST_TABLE_NAME "IEC104SLAVE_CONST_TABLE"

//
#define IEC104_CONST_TOPOLOGY_FILE_IOA "TOPOLOGY_FILE_IOA"
#define IEC104_CONST_CCS_IEC104_C6IP "CCS_IEC104_C6IP"
#define IEC104_CONST_CCS_SLAVE_C6PORT "CCS_SLAVE_C6PORT"
#define IEC104_CONST_CCS_UPLOAD_C6PORT "CCS_UPLOAD_C6PORT"
#define IEC104_CONST_SOE_ENABLED "SOE_ENABLED"
#define IEC104_CONST_TEST_FR_TIMEOUT "TEST_FR_TIMEOUT"
#define IEC104_CONST_TEST_SOE_DB_TABLES "TEST_SOE_DB_TABLES"
#define IEC104_CONST_BB_PVINVERTER "BB_PVINVERTER"
//#define IEC104_CONST_CLIENT_OR_SERVER "CLIENT_OR_SERVER"
#define IEC104_CONST_FUNCTION_CODE "FUNCTION_CODE"

#endif //APP_CONST_IEC104_H
