CREATE TABLE `CONST_TABLE`
(
    `CONST_ID`    INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    `CONST_KEY`   TEXT    NOT NULL DEFAULT '',
    `CONST_VALUE` TEXT    NOT NULL DEFAULT '',
    `RES1`        text    NOT NULL DEFAULT '',
    `RES2`        text    NOT NULL DEFAULT '',
    `RES3`        text    NOT NULL DEFAULT ''
);
